// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleExport.App.DAL;

#nullable disable

namespace VehicleExport.App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole<long>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9770d744-5c62-4d76-a4ef-163f94b33dad"),
                            ConcurrencyStamp = "ba3dab83-e5a7-4058-966f-0b6144eec781",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("558669b9-49a9-4520-90b8-51ba5b12c33e"),
                            ConcurrencyStamp = "bae50c46-ddfb-4322-8d28-84dd2831db15",
                            Name = "ProjectManager",
                            NormalizedName = "ProjectManager"
                        },
                        new
                        {
                            Id = new Guid("b67f4c23-5886-41ee-bbbb-6ae377f8f2ad"),
                            ConcurrencyStamp = "19d42f1a-0316-4166-bc88-8192daddccfa",
                            Name = "ProjectViewer",
                            NormalizedName = "ProjectViewer"
                        },
                        new
                        {
                            Id = new Guid("18b6e930-29db-4c03-88e9-840adf59f2f7"),
                            ConcurrencyStamp = "a947937b-c795-4ab1-ad96-db6f24677f30",
                            Name = "ContentManager",
                            NormalizedName = "ContentManager"
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1479067a-e332-4010-9d52-8ef9a7eeabf4",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEOvcxAXN5tuEzAVCzTDr9dsijI+zSPJOlGuRt/nm09rMb6elXM4nvMIt3Ypxwt7VxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be"),
                            RoleId = new Guid("9770d744-5c62-4d76-a4ef-163f94b33dad"),
                            Id = new Guid("855f5acc-46a3-4803-a6c5-0b1a7af77dbd")
                        },
                        new
                        {
                            UserId = new Guid("c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be"),
                            RoleId = new Guid("558669b9-49a9-4520-90b8-51ba5b12c33e"),
                            Id = new Guid("b778e0bc-7a2b-41b9-9e16-5a2240597966")
                        },
                        new
                        {
                            UserId = new Guid("c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be"),
                            RoleId = new Guid("b67f4c23-5886-41ee-bbbb-6ae377f8f2ad"),
                            Id = new Guid("157d137f-0491-4d8d-89cc-e492368d5fe3")
                        },
                        new
                        {
                            UserId = new Guid("c9db7b0d-5889-4a71-b1a9-cf59ef2fa4be"),
                            RoleId = new Guid("18b6e930-29db-4c03-88e9-840adf59f2f7"),
                            Id = new Guid("1daf52d1-447d-4565-b099-ea67e5d1d40d")
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ExternalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provider")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ExternalCredentials");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Content.ContentBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedTokens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.ToTable("ContentBlocks", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            Id = new Guid("1216cb5d-7047-4c64-8ac5-86627898ac3e"),
                            AllowedTokens = "[{\"Token\":\"passwordResetUrl\",\"Description\":\"The URL for the user to reset their password\"}]",
                            Description = "The text that appears in a password reset message",
                            IsPage = false,
                            Slug = "password-reset-email",
                            Title = "Reset Your Password",
                            Value = "To reset your account, follow this link: %passwordResetUrl%"
                        },
                        new
                        {
                            Id = new Guid("0b351158-ad87-499f-945b-1e61373e2e45"),
                            Description = "The text that appears on the About page",
                            IsPage = true,
                            Slug = "about",
                            Title = "About Us",
                            Value = "About us..."
                        },
                        new
                        {
                            Id = new Guid("30ee8fe7-fd3e-4f86-ae39-cae419a0bacc"),
                            Description = "",
                            IsPage = true,
                            Slug = "placeholder",
                            Title = "Placeholder",
                            Value = "This is a placeholder page. The underlying functionality has not yet been implemented."
                        },
                        new
                        {
                            Id = new Guid("20c6ab53-0c44-4f8d-ae2d-51721ed9b785"),
                            Description = "Content that appears on the Home/Dashboard page",
                            IsPage = false,
                            Slug = "dashboard",
                            Title = "Hello",
                            Value = "Hello, world. Or whoever else is here. This content is editable within the app."
                        },
                        new
                        {
                            Id = new Guid("9a13d562-8732-41a2-9c22-4fb88fa78969"),
                            Description = "The help page that appears in the top nav",
                            IsPage = true,
                            Slug = "help",
                            Title = "Help!",
                            Value = "Need help? Don't we all."
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.DatabaseFields.DatabaseField", b =>
                {
                    b.Property<int>("DatabaseFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseFieldId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SqlText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("DatabaseFieldId");

                    b.ToTable("DatabaseFields", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Destinations.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<short>("EncryptionProtocolTypeId")
                        .HasColumnType("smallint");

                    b.Property<short>("EncryptionTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("FtpHost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FtpPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FtpRemoteDir")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FtpUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IncludeHeaders")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("OneFilePerDealer")
                        .HasColumnType("bit");

                    b.Property<string>("OutputFileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("OutputFormatTypeId")
                        .HasColumnType("smallint");

                    b.Property<short>("ProtocolTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("SSHKeyFileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("SendPhotosInZip")
                        .HasColumnType("bit");

                    b.Property<string>("SshFilePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseQuotedFields")
                        .HasColumnType("bit");

                    b.Property<bool>("ZipOutputFile")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtmLastChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("DestinationId");

                    b.HasIndex("EncryptionProtocolTypeId");

                    b.HasIndex("EncryptionTypeId");

                    b.HasIndex("OutputFormatTypeId");

                    b.HasIndex("ProtocolTypeId");

                    b.ToTable("Destinations", (string)null);

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            EncryptionProtocolTypeId = (short)1,
                            EncryptionTypeId = (short)1,
                            FtpHost = "vendor.windowstickers.biz",
                            FtpPassword = "somepassword",
                            FtpRemoteDir = "/",
                            FtpUsername = "someuser",
                            IncludeHeaders = true,
                            Name = "Test Destination 1",
                            OneFilePerDealer = false,
                            OutputFileName = "Vehicledata.txt",
                            OutputFormatTypeId = (short)2,
                            ProtocolTypeId = (short)1,
                            SendPhotosInZip = false,
                            UseQuotedFields = true,
                            ZipOutputFile = false,
                            dtmCreated = new DateTime(2023, 9, 19, 18, 13, 58, 164, DateTimeKind.Local).AddTicks(8489),
                            dtmLastChanged = new DateTime(2023, 9, 19, 18, 13, 58, 164, DateTimeKind.Local).AddTicks(8525)
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.ExportDealerParameters.ExportDealerParameter", b =>
                {
                    b.Property<int>("ExportDealerParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportDealerParameterId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<int>("ExportId")
                        .HasColumnType("int");

                    b.Property<int>("LayoutFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("ExportDealerParameterId");

                    b.HasIndex("LayoutFieldId");

                    b.ToTable("ExportDealerParameters", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.ExportDealers.ExportDealer", b =>
                {
                    b.Property<int>("ExportDealerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportDealerId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<int>("ExportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("ExportDealerId");

                    b.HasIndex("ExportId");

                    b.HasIndex("ExportId", "DealerId");

                    b.ToTable("ExportDealers", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.Export", b =>
                {
                    b.Property<int>("ExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("LayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<TimeSpan?>("RunTimeOne")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("RunTimeTwo")
                        .HasColumnType("time");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtmLastChanged")
                        .HasColumnType("datetime2");

                    b.HasKey("ExportId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("LayoutId");

                    b.ToTable("Exports", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));

                    b.HasData(
                        new
                        {
                            ExportId = 1,
                            DestinationId = 1,
                            LayoutId = 1,
                            Name = "Sample Export 1",
                            RunTimeOne = new TimeSpan(0, 0, 0, 0, 0),
                            dtmCreated = new DateTime(2023, 9, 19, 18, 13, 58, 164, DateTimeKind.Local).AddTicks(8555),
                            dtmLastChanged = new DateTime(2023, 9, 19, 18, 13, 58, 164, DateTimeKind.Local).AddTicks(8557)
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.ExportTracking", b =>
                {
                    b.Property<int>("ExportTrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportTrackingId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExportId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("int");

                    b.HasKey("ExportTrackingId");

                    b.HasIndex("ExportId");

                    b.ToTable("ExportTracking", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.ExportTrackingDealer", b =>
                {
                    b.Property<int>("ExportTrackingDealerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportTrackingDealerId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<int>("ExportTrackingId")
                        .HasColumnType("int");

                    b.Property<short>("PhotoCount")
                        .HasColumnType("smallint");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("int");

                    b.HasKey("ExportTrackingDealerId");

                    b.HasIndex("ExportTrackingId", "DealerId");

                    b.ToTable("ExportTrackingDealer", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ended")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExpectedCount")
                        .HasColumnType("bigint");

                    b.Property<long>("FailureCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("SerializedItemIds")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ItemIds");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("datetime2");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.ToTable("Jobs", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Jobs.JobItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobItems", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }
                    ));
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.LayoutFields.LayoutField", b =>
                {
                    b.Property<int>("LayoutFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LayoutFieldId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("DatabaseFieldId")
                        .HasColumnType("int");

                    b.Property<short>("LayoutFieldTypeId")
                        .HasColumnType("smallint");

                    b.Property<int>("LayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Parameter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("LayoutFieldId");

                    b.HasIndex("DatabaseFieldId");

                    b.HasIndex("LayoutId");

                    b.ToTable("LayoutFields", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.LayoutFieldsMap.LayoutFieldMap", b =>
                {
                    b.Property<int>("LayoutFieldsMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LayoutFieldsMapId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<short>("FieldOrder")
                        .HasColumnType("smallint");

                    b.Property<int?>("LayoutFieldId")
                        .HasColumnType("int");

                    b.Property<int>("LayoutId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceholderLabel")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("LayoutFieldsMapId");

                    b.HasIndex("LayoutFieldId");

                    b.HasIndex("LayoutId");

                    b.ToTable("LayoutFieldsMap", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.LayoutFilters.LayoutFilter", b =>
                {
                    b.Property<int>("LayoutId")
                        .HasColumnType("int");

                    b.Property<bool>("CertifiedOnly")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("MakesList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NewVehicles")
                        .HasColumnType("bit");

                    b.Property<string>("ProductsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsedVehicles")
                        .HasColumnType("bit");

                    b.Property<string>("WarrantiesList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("LayoutId");

                    b.ToTable("LayoutFilters", (string)null);
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Layouts.Layout", b =>
                {
                    b.Property<int>("LayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LayoutId"), 1L, 1);

                    b.Property<byte[]>("ConcurrencyTimestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoredProcedureName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("dtmCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("LayoutId");

                    b.ToTable("Layouts", (string)null);

                    b.HasData(
                        new
                        {
                            LayoutId = 1,
                            Name = "Sample Layout 1",
                            dtmCreated = new DateTime(2023, 9, 19, 18, 13, 58, 164, DateTimeKind.Local).AddTicks(8539)
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.EncryptionProtocolType", b =>
                {
                    b.Property<short>("EncryptionProtocolTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("EncryptionProtocolTypeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncryptionProtocolTypeId");

                    b.ToTable("EncryptionProtocolType", (string)null);

                    b.HasData(
                        new
                        {
                            EncryptionProtocolTypeId = (short)1,
                            Description = "Explicit FTP over TLS"
                        },
                        new
                        {
                            EncryptionProtocolTypeId = (short)2,
                            Description = "Plain FTP"
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.EncryptionType", b =>
                {
                    b.Property<short>("EncryptionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("EncryptionTypeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EncryptionTypeId");

                    b.ToTable("EncryptionType", (string)null);

                    b.HasData(
                        new
                        {
                            EncryptionTypeId = (short)1,
                            Description = "Active"
                        },
                        new
                        {
                            EncryptionTypeId = (short)2,
                            Description = "Passive"
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.LayoutFieldType", b =>
                {
                    b.Property<short>("LayoutFieldTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("LayoutFieldTypeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LayoutFieldTypeId");

                    b.ToTable("LayoutFieldType", (string)null);

                    b.HasData(
                        new
                        {
                            LayoutFieldTypeId = (short)1,
                            Description = "SQL"
                        },
                        new
                        {
                            LayoutFieldTypeId = (short)2,
                            Description = "Parameter"
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.OutputFormatType", b =>
                {
                    b.Property<short>("OutputFormatTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("OutputFormatTypeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutputFormatTypeId");

                    b.ToTable("OutputFormatType", (string)null);

                    b.HasData(
                        new
                        {
                            OutputFormatTypeId = (short)1,
                            Description = "Comma-Separated (CSV)"
                        },
                        new
                        {
                            OutputFormatTypeId = (short)2,
                            Description = "Tab-Delimited (TAB)"
                        },
                        new
                        {
                            OutputFormatTypeId = (short)3,
                            Description = "Pipe-Delimited"
                        });
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.ProtocolType", b =>
                {
                    b.Property<short>("ProtocolTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ProtocolTypeId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProtocolTypeId");

                    b.ToTable("ProtocolType", (string)null);

                    b.HasData(
                        new
                        {
                            ProtocolTypeId = (short)1,
                            Description = "Plain FTP"
                        },
                        new
                        {
                            ProtocolTypeId = (short)2,
                            Description = "FTP+SSH"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ApplicationUserRole", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationRole", "ApplicationRole")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationUser", "ApplicationUser")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ExternalCredential", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Accounts.ApplicationUser", "ApplicationUser")
                        .WithMany("ExternalCredentials")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Destinations.Destination", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.MinorEntity.EncryptionProtocolType", "EncryptionProtocolType")
                        .WithMany("Destinations")
                        .HasForeignKey("EncryptionProtocolTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleExport.App.Models.Data.MinorEntity.EncryptionType", "EncryptionType")
                        .WithMany("Destinations")
                        .HasForeignKey("EncryptionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleExport.App.Models.Data.MinorEntity.OutputFormatType", "OutputFormatType")
                        .WithMany("Destinations")
                        .HasForeignKey("OutputFormatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleExport.App.Models.Data.MinorEntity.ProtocolType", "ProtocolType")
                        .WithMany("Destinations")
                        .HasForeignKey("ProtocolTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncryptionProtocolType");

                    b.Navigation("EncryptionType");

                    b.Navigation("OutputFormatType");

                    b.Navigation("ProtocolType");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.ExportDealerParameters.ExportDealerParameter", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.LayoutFields.LayoutField", "LayoutField")
                        .WithMany()
                        .HasForeignKey("LayoutFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutField");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.ExportDealers.ExportDealer", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Exports.Export", null)
                        .WithMany("ExportDealer")
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.Export", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Destinations.Destination", "Destination")
                        .WithMany("Exports")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleExport.App.Models.Data.Layouts.Layout", "Layout")
                        .WithMany("Exports")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.ExportTracking", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Exports.Export", null)
                        .WithMany("ExportTracking")
                        .HasForeignKey("ExportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.ExportTrackingDealer", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Exports.ExportTracking", null)
                        .WithMany("ExportTrackingDealer")
                        .HasForeignKey("ExportTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Jobs.JobItem", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Jobs.Job", "Job")
                        .WithMany("JobItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.LayoutFields.LayoutField", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.DatabaseFields.DatabaseField", "DatabaseField")
                        .WithMany()
                        .HasForeignKey("DatabaseFieldId");

                    b.Navigation("DatabaseField");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.LayoutFieldsMap.LayoutFieldMap", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.LayoutFields.LayoutField", "LayoutField")
                        .WithMany()
                        .HasForeignKey("LayoutFieldId");

                    b.HasOne("VehicleExport.App.Models.Data.Layouts.Layout", "Layout")
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");

                    b.Navigation("LayoutField");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.LayoutFilters.LayoutFilter", b =>
                {
                    b.HasOne("VehicleExport.App.Models.Data.Layouts.Layout", "Layout")
                        .WithOne("LayoutFilter")
                        .HasForeignKey("VehicleExport.App.Models.Data.LayoutFilters.LayoutFilter", "LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ApplicationRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Accounts.ApplicationUser", b =>
                {
                    b.Navigation("ExternalCredentials");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Destinations.Destination", b =>
                {
                    b.Navigation("Exports");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.Export", b =>
                {
                    b.Navigation("ExportDealer");

                    b.Navigation("ExportTracking");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Exports.ExportTracking", b =>
                {
                    b.Navigation("ExportTrackingDealer");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Jobs.Job", b =>
                {
                    b.Navigation("JobItems");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.Layouts.Layout", b =>
                {
                    b.Navigation("Exports");

                    b.Navigation("LayoutFilter");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.EncryptionProtocolType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.EncryptionType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.OutputFormatType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("VehicleExport.App.Models.Data.MinorEntity.ProtocolType", b =>
                {
                    b.Navigation("Destinations");
                });
#pragma warning restore 612, 618
        }
    }
}
